### ISSUE TITLE
base32 to base64 conversion support

### ISSUE THREAD

**Issue by abl** [al177/twostep#1]
Hiya!

http://github.com/aleksandyr/pTOTP might be useful to you - the (Apache 2.0 licensed) Google Authenticator has an implementation that was trivial to port over to Pebble.

**Comment by al177** [comment]
Yeah, it probably wasn't a good idea to suggest using another site to do the key conversion.  I'm removing that recommendation for the moment and will look at the Authenticator code later when I've got a few minutes.  Thanks!
